version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videoteca
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres", "-d", "videoteca"]
        interval: 30s
        timeout: 10s
        retries: 5

  server:
    build:
      context: .
      dockerfile: ./backend/dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: videoteca
    ports:
      - "8080:8080"

volumes:
  db_data:

