openapi: 3.0.4
info:
  title: MyVideoteca API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - endpoint
                - email
                - password
              properties:
                endpoint:
                  type: string
                  pattern: '^login$'
                email:
                  type: string
                  pattern: '^[a-zA-Z0-9.%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$'
                password:
                  type: string
      responses:
        '200':
          description: Login effettuato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  id:
                    type: integer
                  numero_film_non_restituiti:
                    type: integer
                  max_noleggi:
                    type: integer
                  film_non_restituiti:
                    type: boolean
                  token:
                    type: string
                    description: JWT token
        '400':
          description: Login fallito
  /signup:
    post:
      summary: Registrazione
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - endpoint
                - email
                - password
                - nome
                - cognome
              properties:
                endpoint:
                  type: string
                  pattern: '^signup$'
                email:
                  type: string
                password:
                  type: string
                nome:
                  type: string
                cognome:
                  type: string
      responses:
        '200':
          description: Registrazione completata con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '400':
          description: Registrazione fallita

  /ricerca:
    post:
      summary: Ricerca di film
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token JWT
                titolo:
                  type: string
                genere:
                  type: string
                regista:
                  type: string
                anno:
                  type: integer
                durata_min:
                  type: integer
                durata_max:
                  type: integer
                popolari:
                  type: boolean
      responses:
        '200':
          description: Lista di film
          content:
            application/json:
              schema:
                type: object
                properties:
                  films:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        titolo:
                          type: string
                        genere:
                          type: string
                        regista:
                          type: string
                        anno:
                          type: integer
                        durata:
                          type: integer
                        descrizione:
                          type: string
                        numero_copie:
                          type: integer
                        numero_copie_disponibili:
                          type: integer
        '400':
          description: Token jwt mancante o scaduto
          
  /noleggio:
    post:
      summary: Noleggio di film
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - films
              properties:
                user_id:
                  type: integer
                films:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: Risultato del noleggio
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  successful_rentals:
                    type: array
                    items:
                      type: object
                  failed_rentals:
                    type: array
                    items:
                      type: object

  /restituzione:
    post:
      summary: Restituzione di un film noleggiato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - rental_id
              properties:
                rental_id:
                  type: string
      responses:
        '200':
          description: Return success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  noleggio_id:
                    type: integer
        '400':
          description: Dati per la restituzione non validi
        '404':
          description: Nessun noleggio attivo trovato

  /get_noleggi:
    post:
      summary: Lista dei noleggi attivi di un utente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userid
              properties:
                userid:
                  type: string
      responses:
        '200':
          description: Noleggi attivi dell'utente
          content:
            application/json:
              schema:
                type: object
                properties:
                  noleggi:
                    type: array
                    items:
                      type: object
                      properties:
                        noleggio_id:
                          type: integer
                        film_id:
                          type: integer
                        data_noleggio:
                          type: string
                        data_scadenza:
                          type: string
                        titolo_film:
                          type: string
                        regista_film:
                          type: string