FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    git \
    cmake \
    python3 \
    python3-pip \
    python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get install libjwt-dev -y

RUN python3 -m pip install --user pipx \
    && python3 -m pipx ensurepath

ENV PATH="/root/.local/bin:$PATH"

RUN pipx install conan

WORKDIR /app

COPY . .

RUN conan install . --output-folder=dependencies --build=missing && \
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=release && \
RUN cmake --build build

EXPOSE 8080

CMD ["./build/bin/server"]